apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: usecase1-subscription1
  namespace: usecase1-app
  labels:
    app: usecase1-app
spec:
  channel: usecase1-channel/usecase1
  overrides:
    - clusterName: /
      clusterOverrides:
        - path: metadata.namespace
          value: usecase1-app
  placement:
    placementRef:
      name: usecase1-placement
      kind: PlacementRule